### PR TITLE
build: use zoslib_include_dir provided by node-gyp

### PR DESCRIPTION
**Pull request by alexcfyung**
Use `zoslib_include_dir` variable to get zoslib header files, which allow node.js to dynamically search for it instead of completely rely on user input.

Depends on https://github.com/ibmruntimes/node-zos/pull/13 and https://github.com/ibmruntimes/node-gyp/pull/1

Used to be part of https://github.com/ibmruntimes/node-zos/pull/13, but since it require https://github.com/ibmruntimes/node-gyp/pull/1, I separate it into 2 PR.

##### Checklist

- [ ] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Review by richardlau — APPROVED** [review]

**Review by gabylb — APPROVED** [review]
LGTM

**Review by joransiu — APPROVED** [review]
LGTM

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Review by zsw007 — COMMENTED** [review]
```
Error: not ok 4 subsystem: Invalid subsystem: "gypi" (gypi: set include_dirs on z/OS)
  ---
    {
      found: 'gypi: set include_dirs on z/OS',
      compare: 'indexOf() !== -1',
      wanted: [
        'benchmark',      'build',    'bootstrap',   'cli',
        'deps',           'doc',      'errors',      'etw',
        'esm',            'gyp',      'inspector',   'lib',
        'loader',         'meta',     'msi',         'node',
        'node-api',       'perfctr',  'policy',      'src',
        'test',           'tools',    'typings',     'wasm',
        'win',            'assert',   'async_hooks', 'buffer',
        'child_process',  'cluster',  'console',     'constants',
        'crypto',         'debugger', 'dgram',       'dns',
        'domain',         'events',   'fs',          'http',
        'http2',          'https',    'inspector',   'module',
        'net',            'os',       'path',        'perf_hooks',
        'process',        'punycode', 'querystring', 'quic',
        'readline',       'repl',     'report',      'stream',
        'string_decoder', 'sys',      'timers',      'tls',
        'trace_events',   'tty',      'url',         'util',
        'v8',             'vm',       'wasi',        'worker',
        'zlib'
      ],
      at: { line: 0, column: 0, body: undefined }
    }
  ...
```

Maybe change prefix to `gyp` instead? Or maybe it could also be considered `build`.

**Comment by alexcfyung** [comment]
> ```
> Error: not ok 4 subsystem: Invalid subsystem: "gypi" (gypi: set include_dirs on z/OS)
>   ---
>     {
>       found: 'gypi: set include_dirs on z/OS',
>       compare: 'indexOf() !== -1',
>       wanted: [
>         'benchmark',      'build',    'bootstrap',   'cli',
>         'deps',           'doc',      'errors',      'etw',
>         'esm',            'gyp',      'inspector',   'lib',
>         'loader',         'meta',     'msi',         'node',
>         'node-api',       'perfctr',  'policy',      'src',
>         'test',           'tools',    'typings',     'wasm',
>         'win',            'assert',   'async_hooks', 'buffer',
>         'child_process',  'cluster',  'console',     'constants',
>         'crypto',         'debugger', 'dgram',       'dns',
>         'domain',         'events',   'fs',          'http',
>         'http2',          'https',    'inspector',   'module',
>         'net',            'os',       'path',        'perf_hooks',
>         'process',        'punycode', 'querystring', 'quic',
>         'readline',       'repl',     'report',      'stream',
>         'string_decoder', 'sys',      'timers',      'tls',
>         'trace_events',   'tty',      'url',         'util',
>         'v8',             'vm',       'wasi',        'worker',
>         'zlib'
>       ],
>       at: { line: 0, column: 0, body: undefined }
>     }
>   ...
> ```
> 
> Maybe change prefix to `gyp` instead? Or maybe it could also be considered `build`.

I will squash the commit so the prefix will be "build"

**Review by zsw007 — APPROVED** [review]
LGTM

**Pull request merged**
